#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Squash_WhirlwindBlast

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Squash_WhirlwindBlast.AbilityTooltip_Squash_WhirlwindBlast_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Squash_WhirlwindBlast_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Squash_WhirlwindBlast_C">();
	}
	static class UAbilityTooltip_Squash_WhirlwindBlast_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Squash_WhirlwindBlast_C>();
	}
};

}

