#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Grape_BrambleShield

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Grape_BrambleShield.AbilityTooltip_Grape_BrambleShield_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Grape_BrambleShield_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Grape_BrambleShield_C">();
	}
	static class UAbilityTooltip_Grape_BrambleShield_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Grape_BrambleShield_C>();
	}
};

}

