#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Date_ChainLightning

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Date_ChainLightning.AbilityTooltip_Date_ChainLightning_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Date_ChainLightning_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Date_ChainLightning_C">();
	}
	static class UAbilityTooltip_Date_ChainLightning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Date_ChainLightning_C>();
	}
};

}

