#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Soy_Boarding

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Soy_Boarding.AbilityTooltip_Soy_Boarding_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Soy_Boarding_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Soy_Boarding_C">();
	}
	static class UAbilityTooltip_Soy_Boarding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Soy_Boarding_C>();
	}
};

}

