#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Wasabi_Claws

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Wasabi_Claws.AbilityTooltip_Wasabi_Claws_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Wasabi_Claws_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Wasabi_Claws_C">();
	}
	static class UAbilityTooltip_Wasabi_Claws_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Wasabi_Claws_C>();
	}
};

}

