#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Plum_KineticAbs

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Plum_KineticAbs.AbilityTooltip_Plum_KineticAbs_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Plum_KineticAbs_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Plum_KineticAbs_C">();
	}
	static class UAbilityTooltip_Plum_KineticAbs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Plum_KineticAbs_C>();
	}
};

}

