#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Vertigo_Punch

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Vertigo_Punch.AbilityTooltip_Vertigo_Punch_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Vertigo_Punch_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Vertigo_Punch_C">();
	}
	static class UAbilityTooltip_Vertigo_Punch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Vertigo_Punch_C>();
	}
};

}

