#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Tapas_SkyStrike

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Tapas_SkyStrike.AbilityTooltip_Tapas_SkyStrike_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Tapas_SkyStrike_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Tapas_SkyStrike_C">();
	}
	static class UAbilityTooltip_Tapas_SkyStrike_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Tapas_SkyStrike_C>();
	}
};

}

