#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_HoneyDew_Fist

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_HoneyDew_Fist.AbilityTooltip_HoneyDew_Fist_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_HoneyDew_Fist_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_HoneyDew_Fist_C">();
	}
	static class UAbilityTooltip_HoneyDew_Fist_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_HoneyDew_Fist_C>();
	}
};

}

