#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AbilityTooltip_Tomato_RepulsorCannon

#include "Basic.hpp"

#include "HUD_AbilityInteractionContext_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AbilityTooltip_Tomato_RepulsorCannon.AbilityTooltip_Tomato_RepulsorCannon_C
// 0x0000 (0x0400 - 0x0400)
class UAbilityTooltip_Tomato_RepulsorCannon_C final : public UHUD_AbilityInteractionContext_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AbilityTooltip_Tomato_RepulsorCannon_C">();
	}
	static class UAbilityTooltip_Tomato_RepulsorCannon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityTooltip_Tomato_RepulsorCannon_C>();
	}
};

}

