#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AnimNotifyState_HolsterWeaponWithTag

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "AnimNotifyState_HolsterWeapon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimNotifyState_HolsterWeaponWithTag.AnimNotifyState_HolsterWeaponWithTag_C
// 0x0020 (0x0060 - 0x0040)
class UAnimNotifyState_HolsterWeaponWithTag_C final : public UAnimNotifyState_HolsterWeapon_C
{
public:
	struct FGameplayTagContainer                  SkipHolsterGameplayTags;                           // 0x0040(0x0020)(Edit, BlueprintVisible)

public:
	bool Received_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimNotifyState_HolsterWeaponWithTag_C">();
	}
	static class UAnimNotifyState_HolsterWeaponWithTag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotifyState_HolsterWeaponWithTag_C>();
	}
};

}

