#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AnimNotifyState_StopMontagePlayDate

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimNotifyState_StopMontagePlayDate.AnimNotifyState_StopMontagePlayDate_C
// 0x0000 (0x0030 - 0x0030)
class UAnimNotifyState_StopMontagePlayDate_C final : public UAnimNotifyState
{
public:
	bool Received_NotifyTick(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float FrameDeltaTime) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimNotifyState_StopMontagePlayDate_C">();
	}
	static class UAnimNotifyState_StopMontagePlayDate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotifyState_StopMontagePlayDate_C>();
	}
};

}

