#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Athena_LockOnWidgetActor_Proto

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_LockOnWidgetActor_Proto.Athena_LockOnWidgetActor_Proto_C
// 0x0018 (0x0238 - 0x0220)
class AAthena_LockOnWidgetActor_Proto_C final : public AActor
{
public:
	class UWidgetComponent*                       LockOnWidget;                                      // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       HealthBar;                                         // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_LockOnWidgetActor_Proto_C">();
	}
	static class AAthena_LockOnWidgetActor_Proto_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_LockOnWidgetActor_Proto_C>();
	}
};

}

