#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Athena_PlayerCameraMode_Wasabi

#include "Basic.hpp"

#include "Athena_PlayerCameraModeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_PlayerCameraMode_Wasabi.Athena_PlayerCameraMode_Wasabi_C
// 0x0000 (0x0DD0 - 0x0DD0)
class UAthena_PlayerCameraMode_Wasabi_C final : public UAthena_PlayerCameraModeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_PlayerCameraMode_Wasabi_C">();
	}
	static class UAthena_PlayerCameraMode_Wasabi_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraMode_Wasabi_C>();
	}
};

}

