#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_AirstrikeCameraShaking

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_AirstrikeCameraShaking.B_AirstrikeCameraShaking_C
// 0x0000 (0x0190 - 0x0190)
class UB_AirstrikeCameraShaking_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_AirstrikeCameraShaking_C">();
	}
	static class UB_AirstrikeCameraShaking_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_AirstrikeCameraShaking_C>();
	}
};

}

