#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_BasePetInstance

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_BasePetInstance.B_BasePetInstance_C
// 0x0010 (0x02A0 - 0x0290)
class AB_BasePetInstance_C : public AFortPlayerPet
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 LinkedLayerAnimClass;                              // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void PetMaterialsOverride();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_B_BasePetInstance(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_BasePetInstance_C">();
	}
	static class AB_BasePetInstance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_BasePetInstance_C>();
	}
};

}

