#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_CoreBR_Weap_Parent

#include "Basic.hpp"

#include "B_UtilityItem_Generic_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_CoreBR_Weap_Parent.B_CoreBR_Weap_Parent_C
// 0x0000 (0x0D08 - 0x0D08)
class AB_CoreBR_Weap_Parent_C final : public AB_UtilityItem_Generic_Athena_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_CoreBR_Weap_Parent_C">();
	}
	static class AB_CoreBR_Weap_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_CoreBR_Weap_Parent_C>();
	}
};

}

