#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_GrenadeCameraShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_GrenadeCameraShake.B_GrenadeCameraShake_C
// 0x0000 (0x0190 - 0x0190)
class UB_GrenadeCameraShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_GrenadeCameraShake_C">();
	}
	static class UB_GrenadeCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_GrenadeCameraShake_C>();
	}
};

}

