#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_HighTower_Mango_DualPistol_Auto_Heavy_Athena

#include "Basic.hpp"


namespace SDK::Params
{

// Function B_HighTower_Mango_DualPistol_Auto_Heavy_Athena.B_HighTower_Mango_DualPistol_Auto_Heavy_Athena_C.DeactivateShellsFX
// 0x0001 (0x0001 - 0x0000)
struct B_HighTower_Mango_DualPistol_Auto_Heavy_Athena_C_DeactivateShellsFX final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

