#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Junior_HoloTable_FX_Stage3

#include "Basic.hpp"

#include "B_Junior_HoloTable_FX_Stage3_classes.hpp"
#include "B_Junior_HoloTable_FX_Stage3_parameters.hpp"


namespace SDK
{

// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.ExecuteUbergraph_B_Junior_HoloTable_FX_Stage3
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Junior_HoloTable_FX_Stage3_C::ExecuteUbergraph_B_Junior_HoloTable_FX_Stage3(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "ExecuteUbergraph_B_Junior_HoloTable_FX_Stage3");

	Params::B_Junior_HoloTable_FX_Stage3_C_ExecuteUbergraph_B_Junior_HoloTable_FX_Stage3 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.ResetFadeOut
// (BlueprintCallable, BlueprintEvent)

void AB_Junior_HoloTable_FX_Stage3_C::ResetFadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "ResetFadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Junior_HoloTable_FX_Stage3_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Junior_HoloTable_FX_Stage3_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "ReceiveTick");

	Params::B_Junior_HoloTable_FX_Stage3_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.Timeline_FadeOut__UpdateFunc
// (BlueprintEvent)

void AB_Junior_HoloTable_FX_Stage3_C::Timeline_FadeOut__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "Timeline_FadeOut__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.Timeline_FadeOut__FinishedFunc
// (BlueprintEvent)

void AB_Junior_HoloTable_FX_Stage3_C::Timeline_FadeOut__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "Timeline_FadeOut__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Junior_HoloTable_FX_Stage3.B_Junior_HoloTable_FX_Stage3_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Junior_HoloTable_FX_Stage3_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Junior_HoloTable_FX_Stage3_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

