#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_LowTower_HeldObject_Chaplin_ChargeProjectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prj_NPC_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_LowTower_HeldObject_Chaplin_ChargeProjectile.B_LowTower_HeldObject_Chaplin_ChargeProjectile_C
// 0x0008 (0x0978 - 0x0970)
class AB_LowTower_HeldObject_Chaplin_ChargeProjectile_C final : public APrj_NPC_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_LowTower_HeldObject_Chaplin_ChargeProjectile_C; // 0x0970(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_B_LowTower_HeldObject_Chaplin_ChargeProjectile(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_LowTower_HeldObject_Chaplin_ChargeProjectile_C">();
	}
	static class AB_LowTower_HeldObject_Chaplin_ChargeProjectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_LowTower_HeldObject_Chaplin_ChargeProjectile_C>();
	}
};

}

