#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_LowTower_HeldObject_Chaplin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_Ranged_Generic_classes.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_LowTower_HeldObject_Chaplin.B_LowTower_HeldObject_Chaplin_C
// 0x0010 (0x12A8 - 0x1298)
class AB_LowTower_HeldObject_Chaplin_C final : public AB_Ranged_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_LowTower_HeldObject_Chaplin_C;    // 0x1298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         BattleLabHudKeyDataIndex;                          // 0x12A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_LowTower_HeldObject_Chaplin(int32 EntryPoint);
	void GameplayCue_Abilities_LowTower_Chaplin_PrimaryShoot(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void OnWeaponAttached();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_LowTower_HeldObject_Chaplin_C">();
	}
	static class AB_LowTower_HeldObject_Chaplin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_LowTower_HeldObject_Chaplin_C>();
	}
};

}

