#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Pistol_Revolver_Futuristic_Athena

#include "Basic.hpp"

#include "B_Pistol_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Pistol_Revolver_Futuristic_Athena.B_Pistol_Revolver_Futuristic_Athena_C
// 0x0010 (0x12A8 - 0x1298)
class AB_Pistol_Revolver_Futuristic_Athena_C final : public AB_Pistol_Generic_C
{
public:
	class UStaticMeshComponent*                   Reload_QuickReload;                                // 0x1298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Reload_Ammo;                                       // 0x12A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Pistol_Revolver_Futuristic_Athena_C">();
	}
	static class AB_Pistol_Revolver_Futuristic_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Pistol_Revolver_Futuristic_Athena_C>();
	}
};

}

