#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_RocketLauncher_Generic_Athena_HighTier

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_RocketLauncher_Generic_Athena_HighTier.B_RocketLauncher_Generic_Athena_HighTier_C
// 0x0028 (0x12C0 - 0x1298)
class AB_RocketLauncher_Generic_Athena_HighTier_C final : public AB_Ranged_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_RocketLauncher_Generic_Athena_HighTier_C; // 0x1298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        RearMuzzleLoc;                                     // 0x12A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFXSystemAsset*                         RearMuzzleFXSystem;                                // 0x12A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	struct FVector                                RearMuzzleOffsetMultiplier;                        // 0x12B0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_RocketLauncher_Generic_Athena_HighTier(int32 EntryPoint);
	void Muzzle_Flash_FX(bool Persistent_Fire);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_RocketLauncher_Generic_Athena_HighTier_C">();
	}
	static class AB_RocketLauncher_Generic_Athena_HighTier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_RocketLauncher_Generic_Athena_HighTier_C>();
	}
};

}

