#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPurchaseScreenSelector

#include "Basic.hpp"

#include "BattlePassPurchaseScreenSelector_classes.hpp"
#include "BattlePassPurchaseScreenSelector_parameters.hpp"


namespace SDK
{

// Function BattlePassPurchaseScreenSelector.BattlePassPurchaseScreenSelector_C.ExecuteUbergraph_BattlePassPurchaseScreenSelector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreenSelector_C::ExecuteUbergraph_BattlePassPurchaseScreenSelector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPurchaseScreenSelector_C", "ExecuteUbergraph_BattlePassPurchaseScreenSelector");

	Params::BattlePassPurchaseScreenSelector_C_ExecuteUbergraph_BattlePassPurchaseScreenSelector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreenSelector.BattlePassPurchaseScreenSelector_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassPurchaseScreenSelector_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPurchaseScreenSelector_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

