#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPurchaseScreenSelector

#include "Basic.hpp"


namespace SDK::Params
{

// Function BattlePassPurchaseScreenSelector.BattlePassPurchaseScreenSelector_C.ExecuteUbergraph_BattlePassPurchaseScreenSelector
// 0x0004 (0x0004 - 0x0000)
struct BattlePassPurchaseScreenSelector_C_ExecuteUbergraph_BattlePassPurchaseScreenSelector final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

