#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPurchaseScreenSelector

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BattlePassPurchaseScreenSelector.BattlePassPurchaseScreenSelector_C
// 0x0008 (0x03D8 - 0x03D0)
class UBattlePassPurchaseScreenSelector_C final : public UAthenaBattlePassPurchaseScreenSelector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BattlePassPurchaseScreenSelector(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BattlePassPurchaseScreenSelector_C">();
	}
	static class UBattlePassPurchaseScreenSelector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassPurchaseScreenSelector_C>();
	}
};

}

