#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BB_SecondaryPower

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BB_SecondaryPower.BB_SecondaryPower_C
// 0x0000 (0x00F8 - 0x00F8)
class UBB_SecondaryPower_C final : public UFortMobileActionButtonBehavior
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BB_SecondaryPower_C">();
	}
	static class UBB_SecondaryPower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBB_SecondaryPower_C>();
	}
};

}

