#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BB_UtilityPower

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BB_UtilityPower.BB_UtilityPower_C
// 0x0000 (0x00F8 - 0x00F8)
class UBB_UtilityPower_C final : public UFortMobileActionButtonBehavior
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BB_UtilityPower_C">();
	}
	static class UBB_UtilityPower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBB_UtilityPower_C>();
	}
};

}

