#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BGA_CurieFireMesh_FrostedTips_Fireball

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BGA_GenericCurieFuel_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_CurieFireMesh_FrostedTips_Fireball.BGA_CurieFireMesh_FrostedTips_Fireball_C
// 0x0008 (0x0838 - 0x0830)
class ABGA_CurieFireMesh_FrostedTips_Fireball_C final : public ABGA_GenericCurieFuel_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BGA_CurieFireMesh_FrostedTips_Fireball_C; // 0x0830(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BGA_CurieFireMesh_FrostedTips_Fireball(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BGA_CurieFireMesh_FrostedTips_Fireball_C">();
	}
	static class ABGA_CurieFireMesh_FrostedTips_Fireball_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABGA_CurieFireMesh_FrostedTips_Fireball_C>();
	}
};

}

