#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BGA_LowTower_Held_Chaplin_Parent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BGA_HeldWeapon_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_LowTower_Held_Chaplin_Parent.BGA_LowTower_Held_Chaplin_Parent_C
// 0x0010 (0x09B0 - 0x09A0)
class ABGA_LowTower_Held_Chaplin_Parent_C final : public ABGA_HeldWeapon_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BGA_LowTower_Held_Chaplin_Parent_C; // 0x0998(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bHasExploded;                                      // 0x09A0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void ExecuteUbergraph_BGA_LowTower_Held_Chaplin_Parent(int32 EntryPoint);
	void OnExplosionNotify(bool Exploded);
	void OnRep_bHasExploded();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BGA_LowTower_Held_Chaplin_Parent_C">();
	}
	static class ABGA_LowTower_Held_Chaplin_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABGA_LowTower_Held_Chaplin_Parent_C>();
	}
};

}

