#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BGA_CurieFireMesh_FrostedTips_Fireball

#include "Basic.hpp"


namespace SDK::Params
{

// Function BGA_CurieFireMesh_FrostedTips_Fireball.BGA_CurieFireMesh_FrostedTips_Fireball_C.ExecuteUbergraph_BGA_CurieFireMesh_FrostedTips_Fireball
// 0x0004 (0x0004 - 0x0000)
struct BGA_CurieFireMesh_FrostedTips_Fireball_C_ExecuteUbergraph_BGA_CurieFireMesh_FrostedTips_Fireball final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

