#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BGA_LowTower_Held_Chaplin_Parent

#include "Basic.hpp"


namespace SDK::Params
{

// Function BGA_LowTower_Held_Chaplin_Parent.BGA_LowTower_Held_Chaplin_Parent_C.ExecuteUbergraph_BGA_LowTower_Held_Chaplin_Parent
// 0x0008 (0x0008 - 0x0000)
struct BGA_LowTower_Held_Chaplin_Parent_C_ExecuteUbergraph_BGA_LowTower_Held_Chaplin_Parent final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Exploded;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BGA_LowTower_Held_Chaplin_Parent.BGA_LowTower_Held_Chaplin_Parent_C.OnExplosionNotify
// 0x0001 (0x0001 - 0x0000)
struct BGA_LowTower_Held_Chaplin_Parent_C_OnExplosionNotify final
{
public:
	bool                                          Exploded;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

