#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_AIService_Affiliation

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIService_Affiliation.BP_AIService_Affiliation_C
// 0x0000 (0x0188 - 0x0188)
class UBP_AIService_Affiliation_C final : public UAthenaAIServiceAffiliation
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AIService_Affiliation_C">();
	}
	static class UBP_AIService_Affiliation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AIService_Affiliation_C>();
	}
};

}

