#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_CameraShake_HighTower_Grape_BrambleShield_Enter

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraShake_HighTower_Grape_BrambleShield_Enter.BP_CameraShake_HighTower_Grape_BrambleShield_Enter_C
// 0x0000 (0x0190 - 0x0190)
class UBP_CameraShake_HighTower_Grape_BrambleShield_Enter_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CameraShake_HighTower_Grape_BrambleShield_Enter_C">();
	}
	static class UBP_CameraShake_HighTower_Grape_BrambleShield_Enter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShake_HighTower_Grape_BrambleShield_Enter_C>();
	}
};

}

