#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_CameraShake_HighTower_Grape_BrambleShield_Impact

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraShake_HighTower_Grape_BrambleShield_Impact.BP_CameraShake_HighTower_Grape_BrambleShield_Impact_C
// 0x0000 (0x0190 - 0x0190)
class UBP_CameraShake_HighTower_Grape_BrambleShield_Impact_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CameraShake_HighTower_Grape_BrambleShield_Impact_C">();
	}
	static class UBP_CameraShake_HighTower_Grape_BrambleShield_Impact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShake_HighTower_Grape_BrambleShield_Impact_C>();
	}
};

}

