#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Camera_Shake_HighTower_HoneyDew_FistPunchV2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Camera_Shake_HighTower_HoneyDew_FistPunchV2.BP_Camera_Shake_HighTower_HoneyDew_FistPunchV2_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Camera_Shake_HighTower_HoneyDew_FistPunchV2_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Camera_Shake_HighTower_HoneyDew_FistPunchV2_C">();
	}
	static class UBP_Camera_Shake_HighTower_HoneyDew_FistPunchV2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Camera_Shake_HighTower_HoneyDew_FistPunchV2_C>();
	}
};

}

