#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_GrapplingHook_Travel_Mid_Camera

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GrapplingHook_Travel_Mid_Camera.BP_GrapplingHook_Travel_Mid_Camera_C
// 0x0000 (0x0190 - 0x0190)
class UBP_GrapplingHook_Travel_Mid_Camera_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GrapplingHook_Travel_Mid_Camera_C">();
	}
	static class UBP_GrapplingHook_Travel_Mid_Camera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GrapplingHook_Travel_Mid_Camera_C>();
	}
};

}

