#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_TimeSynthTrackComponent_Gasket_Date

#include "Basic.hpp"

#include "BP_TimeSynthTrackComponent_Gasket_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TimeSynthTrackComponent_Gasket_Date.BP_TimeSynthTrackComponent_Gasket_Date_C
// 0x0000 (0x0230 - 0x0230)
class UBP_TimeSynthTrackComponent_Gasket_Date_C final : public UBP_TimeSynthTrackComponent_Gasket_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TimeSynthTrackComponent_Gasket_Date_C">();
	}
	static class UBP_TimeSynthTrackComponent_Gasket_Date_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TimeSynthTrackComponent_Gasket_Date_C>();
	}
};

}

