#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BulletWhipTrackerComponent_StarkRifle

#include "Basic.hpp"

#include "BulletWhipTrackerComponent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BulletWhipTrackerComponent_StarkRifle.BulletWhipTrackerComponent_StarkRifle_C
// 0x0000 (0x00F0 - 0x00F0)
class UBulletWhipTrackerComponent_StarkRifle_C final : public UBulletWhipTrackerComponent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BulletWhipTrackerComponent_StarkRifle_C">();
	}
	static class UBulletWhipTrackerComponent_StarkRifle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletWhipTrackerComponent_StarkRifle_C>();
	}
};

}

