#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CameraMode_HighTower_Wasabi_SpinSlash

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraMode_HighTower_Wasabi_SpinSlash.CameraMode_HighTower_Wasabi_SpinSlash_C
// 0x0000 (0x0138 - 0x0138)
class UCameraMode_HighTower_Wasabi_SpinSlash_C final : public UFort3PCam_Default
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraMode_HighTower_Wasabi_SpinSlash_C">();
	}
	static class UCameraMode_HighTower_Wasabi_SpinSlash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraMode_HighTower_Wasabi_SpinSlash_C>();
	}
};

}

