#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CameraShake_Claws_Swing1

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_Claws_Swing1.CameraShake_Claws_Swing1_C
// 0x0000 (0x0190 - 0x0190)
class UCameraShake_Claws_Swing1_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_Claws_Swing1_C">();
	}
	static class UCameraShake_Claws_Swing1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_Claws_Swing1_C>();
	}
};

}

