#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CameraShake_UncleBrolly_Damage

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_UncleBrolly_Damage.CameraShake_UncleBrolly_Damage_C
// 0x0000 (0x0190 - 0x0190)
class UCameraShake_UncleBrolly_Damage_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_UncleBrolly_Damage_C">();
	}
	static class UCameraShake_UncleBrolly_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_UncleBrolly_Damage_C>();
	}
};

}

