#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CCPM_Hightower_Tapas_Backpack

#include "Basic.hpp"

#include "CCPM_Base_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CCPM_Hightower_Tapas_Backpack.CCPM_Hightower_Tapas_Backpack_C
// 0x0018 (0x0418 - 0x0400)
class ACCPM_Hightower_Tapas_Backpack_C final : public ACCPM_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_CCPM_Hightower_Tapas_Backpack_C;    // 0x0400(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Backpack_Lightning;                                // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Backpack_Sparkles;                                 // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CCPM_Hightower_Tapas_Backpack(int32 EntryPoint);
	void OnPawnAndPartChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CCPM_Hightower_Tapas_Backpack_C">();
	}
	static class ACCPM_Hightower_Tapas_Backpack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACCPM_Hightower_Tapas_Backpack_C>();
	}
};

}

