#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CCPM_EyeFlash_Purple

#include "Basic.hpp"

#include "CCPM_EyeFlash_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CCPM_EyeFlash_Purple.CCPM_EyeFlash_Purple_C
// 0x0000 (0x0488 - 0x0488)
class ACCPM_EyeFlash_Purple_C final : public ACCPM_EyeFlash_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CCPM_EyeFlash_Purple_C">();
	}
	static class ACCPM_EyeFlash_Purple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACCPM_EyeFlash_Purple_C>();
	}
};

}

