#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CCPM_Hightower_Honeydew_Eyes

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CCPM_HoneyDew_Body_Optomized_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CCPM_Hightower_Honeydew_Eyes.CCPM_Hightower_Honeydew_Eyes_C
// 0x0010 (0x04A8 - 0x0498)
class ACCPM_Hightower_Honeydew_Eyes_C final : public ACCPM_HoneyDew_Body_Optomized_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_CCPM_Hightower_Honeydew_Eyes_C;     // 0x0498(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      FX_Eyes;                                           // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveTick(float DeltaSeconds);
	void OnPawnAndPartChanged();
	void ExecuteUbergraph_CCPM_Hightower_Honeydew_Eyes(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CCPM_Hightower_Honeydew_Eyes_C">();
	}
	static class ACCPM_Hightower_Honeydew_Eyes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACCPM_Hightower_Honeydew_Eyes_C>();
	}
};

}

