#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CCPM_Hightower_Honeydew_Eyes

#include "Basic.hpp"


namespace SDK::Params
{

// Function CCPM_Hightower_Honeydew_Eyes.CCPM_Hightower_Honeydew_Eyes_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct CCPM_Hightower_Honeydew_Eyes_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function CCPM_Hightower_Honeydew_Eyes.CCPM_Hightower_Honeydew_Eyes_C.ExecuteUbergraph_CCPM_Hightower_Honeydew_Eyes
// 0x0018 (0x0018 - 0x0000)
struct CCPM_Hightower_Honeydew_Eyes_C_ExecuteUbergraph_CCPM_Hightower_Honeydew_Eyes final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

