#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CommonDialogueRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CommonDialogueRuntime_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function CommonDialogueRuntime.ConversationNode.GetDebugParticipantColor
// 0x0018 (0x0018 - 0x0000)
struct ConversationNode_GetDebugParticipantColor final
{
public:
	struct FGameplayTag                           ParticipantID;                                     // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationChoiceNode.EvaluateChoice
// 0x0038 (0x0038 - 0x0000)
struct ConversationChoiceNode_EvaluateChoice final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	class FText                                   DisplayOption;                                     // 0x0020(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.AdvanceConversation
// 0x0080 (0x0080 - 0x0000)
struct ConversationContextHelpers_AdvanceConversation final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FConversationTaskResult                ReturnValue;                                       // 0x0020(0x0060)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.AdvanceConversationWithChoice
// 0x00A0 (0x00A0 - 0x0000)
struct ConversationContextHelpers_AdvanceConversationWithChoice final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FConversationChoiceReference           Choice;                                            // 0x0020(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FConversationTaskResult                ReturnValue;                                       // 0x0040(0x0060)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.FindConversationComponent
// 0x0010 (0x0010 - 0x0000)
struct ConversationContextHelpers_FindConversationComponent final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConversationParticipantComponent*      ReturnValue;                                       // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.GetConversationInstance
// 0x0028 (0x0028 - 0x0000)
struct ConversationContextHelpers_GetConversationInstance final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	class UConversationInstance*                  ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.GetConversationParticipant
// 0x0030 (0x0030 - 0x0000)
struct ConversationContextHelpers_GetConversationParticipant final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ParticipantTag;                                    // 0x0020(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConversationParticipantComponent*      ReturnValue;                                       // 0x0028(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.GetConversationParticipantActor
// 0x0030 (0x0030 - 0x0000)
struct ConversationContextHelpers_GetConversationParticipantActor final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ParticipantTag;                                    // 0x0020(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 ReturnValue;                                       // 0x0028(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.GetCurrentConversationNodeHandle
// 0x0030 (0x0030 - 0x0000)
struct ConversationContextHelpers_GetCurrentConversationNodeHandle final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FConversationNodeHandle                ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.MakeConversationParticipant
// 0x0030 (0x0030 - 0x0000)
struct ConversationContextHelpers_MakeConversationParticipant final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	class AActor*                                 ParticipantActor;                                  // 0x0020(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ParticipantTag;                                    // 0x0028(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationContextHelpers.PauseConversationAndSendClientChoices
// 0x00B8 (0x00B8 - 0x0000)
struct ConversationContextHelpers_PauseConversationAndSendClientChoices final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FClientConversationMessage             Message;                                           // 0x0020(0x0038)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FConversationTaskResult                ReturnValue;                                       // 0x0058(0x0060)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationLibrary.GetConversationNode
// 0x0018 (0x0018 - 0x0000)
struct ConversationLibrary_GetConversationNode final
{
public:
	struct FConversationNodeHandle                NodeHandle;                                        // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UConversationNode*                ReturnValue;                                       // 0x0010(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationLibrary.StartConversation
// 0x0030 (0x0030 - 0x0000)
struct ConversationLibrary_StartConversation final
{
public:
	struct FGameplayTag                           ConversationEntryTag;                              // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Instigator;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           InstigatorTag;                                     // 0x0010(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Target;                                            // 0x0018(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           TargetTag;                                         // 0x0020(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConversationInstance*                  ReturnValue;                                       // 0x0028(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationParticipantComponent.ClientExecuteTaskAndSideEffects
// 0x0010 (0x0010 - 0x0000)
struct ConversationParticipantComponent_ClientExecuteTaskAndSideEffects final
{
public:
	struct FConversationNodeHandle                Handle;                                            // 0x0000(0x0010)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationParticipantComponent.ClientUpdateConversation
// 0x0068 (0x0068 - 0x0000)
struct ConversationParticipantComponent_ClientUpdateConversation final
{
public:
	struct FClientConversationMessagePayload      Message;                                           // 0x0000(0x0068)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationParticipantComponent.GetParticipantDisplayName
// 0x0018 (0x0018 - 0x0000)
struct ConversationParticipantComponent_GetParticipantDisplayName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationParticipantComponent.RequestServerAdvanceConversation
// 0x0020 (0x0020 - 0x0000)
struct ConversationParticipantComponent_RequestServerAdvanceConversation final
{
public:
	struct FConversationChoiceReference           InChoicePicked;                                    // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationParticipantComponent.ServerAdvanceConversation
// 0x0020 (0x0020 - 0x0000)
struct ConversationParticipantComponent_ServerAdvanceConversation final
{
public:
	struct FConversationChoiceReference           InChoicePicked;                                    // 0x0000(0x0020)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationRequirementNode.IsRequirementSatisfied
// 0x0028 (0x0028 - 0x0000)
struct ConversationRequirementNode_IsRequirementSatisfied final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	EConversationRequirementResult                ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function CommonDialogueRuntime.ConversationSideEffectNode.ClientCauseSideEffect
// 0x0020 (0x0020 - 0x0000)
struct ConversationSideEffectNode_ClientCauseSideEffect final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationSideEffectNode.ServerCauseSideEffect
// 0x0020 (0x0020 - 0x0000)
struct ConversationSideEffectNode_ServerCauseSideEffect final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationTaskNode.ExecuteClientEffects
// 0x0020 (0x0020 - 0x0000)
struct ConversationTaskNode_ExecuteClientEffects final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationTaskNode.ExecuteTaskNode
// 0x0080 (0x0080 - 0x0000)
struct ConversationTaskNode_ExecuteTaskNode final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FConversationTaskResult                ReturnValue;                                       // 0x0020(0x0060)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function CommonDialogueRuntime.ConversationTaskNode.GetNodeBodyColor
// 0x0014 (0x0014 - 0x0000)
struct ConversationTaskNode_GetNodeBodyColor final
{
public:
	struct FLinearColor                           BodyColor;                                         // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function CommonDialogueRuntime.ConversationTaskNode.IsRequirementSatisfied
// 0x0028 (0x0028 - 0x0000)
struct ConversationTaskNode_IsRequirementSatisfied final
{
public:
	struct FConversationContext                   Context;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	EConversationRequirementResult                ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

}

