#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CommonDialogueRuntime

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum CommonDialogueRuntime.EConversationTaskResultType
// NumValues: 0x0005
enum class EConversationTaskResultType : uint8
{
	Invalid                                  = 0,
	AdvanceConversation                      = 1,
	AdvanceConversationWithChoice            = 2,
	PauseConversationAndSendClientChoices    = 3,
	EConversationTaskResultType_MAX          = 4,
};

// Enum CommonDialogueRuntime.EConversationChoiceType
// NumValues: 0x0004
enum class EConversationChoiceType : uint8
{
	Invisible                                = 0,
	UserChoiceAvailable                      = 1,
	UserChoiceUnavailable                    = 2,
	EConversationChoiceType_MAX              = 3,
};

// Enum CommonDialogueRuntime.EConversationRequirementResult
// NumValues: 0x0004
enum class EConversationRequirementResult : uint8
{
	Passed                                   = 0,
	FailedButVisible                         = 1,
	FailedAndHidden                          = 2,
	EConversationRequirementResult_MAX       = 3,
};

// ScriptStruct CommonDialogueRuntime.ConversationContext
// 0x0020 (0x0020 - 0x0000)
struct FConversationContext final
{
public:
	class UConversationInstance*                  ActiveConversation;                                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UConversationParticipantComponent*      ClientParticipant;                                 // 0x0008(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UConversationTaskNode*                  TaskBeingConsidered;                               // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bServer;                                           // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// ScriptStruct CommonDialogueRuntime.ConversationNodeHandle
// 0x0010 (0x0010 - 0x0000)
struct FConversationNodeHandle final
{
public:
	struct FGuid                                  NodeGuid;                                          // 0x0000(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ConversationChoiceReference
// 0x0020 (0x0020 - 0x0000)
struct FConversationChoiceReference final
{
public:
	class FString                                 ChoiceParams;                                      // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FConversationNodeHandle                NodeReference;                                     // 0x0010(0x0010)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ClientConversationMessage
// 0x0038 (0x0038 - 0x0000)
struct FClientConversationMessage final
{
public:
	struct FGameplayTag                           SpeakerID;                                         // 0x0000(0x0008)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   ParticipantDisplayName;                            // 0x0008(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   Text;                                              // 0x0020(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ConversationTaskResult
// 0x0060 (0x0060 - 0x0000)
struct FConversationTaskResult final
{
public:
	EConversationTaskResultType                   Type;                                              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FConversationChoiceReference           Choice;                                            // 0x0008(0x0020)(NativeAccessSpecifierPrivate)
	struct FClientConversationMessage             Message;                                           // 0x0028(0x0038)(NativeAccessSpecifierPrivate)
};

// ScriptStruct CommonDialogueRuntime.CommonDialogueBankParticipant
// 0x0030 (0x0030 - 0x0000)
struct FCommonDialogueBankParticipant final
{
public:
	class FText                                   FallbackName;                                      // 0x0000(0x0018)(NativeAccessSpecifierPublic)
	struct FGameplayTag                           ParticipantName;                                   // 0x0018(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           NodeTint;                                          // 0x0020(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ConversationEntryList
// 0x0010 (0x0010 - 0x0000)
struct FConversationEntryList final
{
public:
	TArray<struct FGuid>                          DestinationList;                                   // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ConversationParticipantEntry
// 0x0010 (0x0010 - 0x0000)
struct FConversationParticipantEntry final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ParticipantID;                                     // 0x0008(0x0008)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ConversationParticipants
// 0x0010 (0x0010 - 0x0000)
struct FConversationParticipants final
{
public:
	TArray<struct FConversationParticipantEntry>  List;                                              // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct CommonDialogueRuntime.ClientConversationOptionEntry
// 0x0040 (0x0040 - 0x0000)
struct FClientConversationOptionEntry final
{
public:
	class FString                                 ChoiceParams;                                      // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   ChoiceText;                                        // 0x0010(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
	EConversationChoiceType                       ChoiceType;                                        // 0x0028(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	struct FConversationNodeHandle                NodeReference;                                     // 0x002C(0x0010)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// ScriptStruct CommonDialogueRuntime.ClientConversationMessagePayload
// 0x0068 (0x0068 - 0x0000)
struct FClientConversationMessagePayload final
{
public:
	struct FClientConversationMessage             Message;                                           // 0x0000(0x0038)(BlueprintVisible, NativeAccessSpecifierPublic)
	struct FConversationParticipants              Participants;                                      // 0x0038(0x0010)(BlueprintVisible, NativeAccessSpecifierPublic)
	struct FConversationNodeHandle                CurrentNode;                                       // 0x0048(0x0010)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FClientConversationOptionEntry> Options;                                           // 0x0058(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

