#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: DataAssetDirectory

#include "Basic.hpp"


namespace SDK
{

// Enum DataAssetDirectory.EDataAssetDirectoryUpdateStatus
// NumValues: 0x0004
enum class EDataAssetDirectoryUpdateStatus : uint8
{
	Failed                                   = 0,
	Success                                  = 1,
	SuccessNoChange                          = 2,
	EDataAssetDirectoryUpdateStatus_MAX      = 3,
};

}

