#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: F_MED_Hightower_Squash_FaceAcc_CtrlRig

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass F_MED_Hightower_Squash_FaceAcc_CtrlRig.F_MED_Hightower_Squash_FaceAcc_CtrlRig_C
// 0x0000 (0x0360 - 0x0360)
class UF_MED_Hightower_Squash_FaceAcc_CtrlRig_C final : public UControlRig
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_Hightower_Squash_FaceAcc_CtrlRig_C">();
	}
	static class UF_MED_Hightower_Squash_FaceAcc_CtrlRig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_Hightower_Squash_FaceAcc_CtrlRig_C>();
	}
};

}

