#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FN_NiagaraNotify

#include "Basic.hpp"

#include "NiagaraAnimNotifies_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FN_NiagaraNotify.FN_NiagaraNotify_C
// 0x0010 (0x00A0 - 0x0090)
class UFN_NiagaraNotify_C final : public UAnimNotify_PlayNiagaraEffect
{
public:
	bool                                          Set_in_Water_Niagara_Variable;                     // 0x0090(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Print_Debug;                                       // 0x0091(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Set_Front_End_Variable;                            // 0x0092(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FN_NiagaraNotify_C">();
	}
	static class UFN_NiagaraNotify_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFN_NiagaraNotify_C>();
	}
};

}

