#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FoleyLib_Hightower_Grape_Bramble

#include "Basic.hpp"

#include "FoleySound_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FoleyLib_Hightower_Grape_Bramble.FoleyLib_Hightower_Grape_Bramble_C
// 0x0000 (0x00B0 - 0x00B0)
class UFoleyLib_Hightower_Grape_Bramble_C final : public UFoleySoundLibrary
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FoleyLib_Hightower_Grape_Bramble_C">();
	}
	static class UFoleyLib_Hightower_Grape_Bramble_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFoleyLib_Hightower_Grape_Bramble_C>();
	}
};

}

