#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FoleySound

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class FoleySound.FoleySoundSubsystem
// 0x00A0 (0x00D0 - 0x0030)
class UFoleySoundSubsystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0xA0];                                      // 0x0030(0x00A0)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void AddLibrary(const class AActor* Actor, TSubclassOf<class UFoleySoundLibrary> Library);
	void RemoveLibrary(const class AActor* Actor, TSubclassOf<class UFoleySoundLibrary> Library);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FoleySoundSubsystem">();
	}
	static class UFoleySoundSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFoleySoundSubsystem>();
	}
};

// Class FoleySound.FoleySoundLibrary
// 0x0088 (0x00B0 - 0x0028)
class UFoleySoundLibrary : public UObject
{
public:
	TMap<struct FGameplayTag, TSoftObjectPtr<class USoundBase>> Sounds;                              // 0x0028(0x0050)(Edit, BlueprintVisible, UObjectWrapper, NativeAccessSpecifierPublic)
	TArray<class USoundBase*>                     LoadedSoundObjects;                                // 0x0078(0x0010)(ZeroConstructor, Transient, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_88[0x28];                                      // 0x0088(0x0028)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FoleySoundLibrary">();
	}
	static class UFoleySoundLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFoleySoundLibrary>();
	}
};

}

