#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FoleySound

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct FoleySound.FoleyActorData
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FFoleyActorData final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

}

