#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_Flopper_Battle_Marking

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_Flopper_Battle_Marking.GA_Athena_Flopper_Battle_Marking_C
// 0x0090 (0x0B38 - 0x0AA8)
class UGA_Athena_Flopper_Battle_Marking_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FScalableFloat                         MarkingRadius;                                     // 0x0AB0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         CurrentMarkingRadius;                              // 0x0AD0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD4[0x4];                                      // 0x0AD4(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	TArray<class AFortPawn*>                      WorkingList;                                       // 0x0AD8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, HasGetValueTypeHash)
	struct FGameplayTag                           CueOnMark;                                         // 0x0AE8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         MarkingDuration;                                   // 0x0AF0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         CurrentMarkingDuration;                            // 0x0B10(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B14[0x4];                                      // 0x0B14(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FScalableFloat                         DisableMarkingPlayers;                             // 0x0B18(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_Athena_Flopper_Battle_Marking(int32 EntryPoint);
	void MarkEnemies_();
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_Flopper_Battle_Marking_C">();
	}
	static class UGA_Athena_Flopper_Battle_Marking_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_Flopper_Battle_Marking_C>();
	}
};

}

