#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_LowGravity_FallDamageImmunity_UsingJump

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GAT_TriggeredAbility_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_LowGravity_FallDamageImmunity_UsingJump.GA_Athena_LowGravity_FallDamageImmunity_UsingJump_C
// 0x0018 (0x0AD8 - 0x0AC0)
class UGA_Athena_LowGravity_FallDamageImmunity_UsingJump_C final : public UGAT_TriggeredAbility_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Athena_LowGravity_FallDamageImmunity_UsingJump_C; // 0x0AC0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         DelayToWaitForGrantedTags;                         // 0x0AC8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DelayToPreventFallDamage;                          // 0x0ACC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        PlayerPawn;                                        // 0x0AD0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Athena_LowGravity_FallDamageImmunity_UsingJump(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_LowGravity_FallDamageImmunity_UsingJump_C">();
	}
	static class UGA_Athena_LowGravity_FallDamageImmunity_UsingJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_LowGravity_FallDamageImmunity_UsingJump_C>();
	}
};

}

