#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_TowerGrenade_Secondary

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Athena_Grenade_ThrowWithTrajectory_Secondary_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_TowerGrenade_Secondary.GA_Athena_TowerGrenade_Secondary_C
// 0x0018 (0x0E68 - 0x0E50)
class UGA_Athena_TowerGrenade_Secondary_C final : public UGA_Athena_Grenade_ThrowWithTrajectory_Secondary_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Athena_TowerGrenade_Secondary_C; // 0x0E50(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_ProjectileTrajectory_C*             ProjectileTrajectoryRed;                           // 0x0E58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 TrajectoryIndicatorRedClass;                       // 0x0E60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Athena_TowerGrenade_Secondary(int32 EntryPoint);
	void UpdateTrajectorySpline();
	void CleanupTrajectory();
	void K2_ActivateAbility();
	bool IsTrajectoryHidden();
	void SetupDummyProjectileRed();
	class AFortProjectileTrajectory* SpawnTrajectoryIndicator(bool bSpawnOnEquip);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_TowerGrenade_Secondary_C">();
	}
	static class UGA_Athena_TowerGrenade_Secondary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_TowerGrenade_Secondary_C>();
	}
};

}

