#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Squash_WhirlwindBlast_Stun

#include "Basic.hpp"

#include "GA_Melee_BlockBreak_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Squash_WhirlwindBlast_Stun.GA_HighTower_Squash_WhirlwindBlast_Stun_C
// 0x0000 (0x0AC8 - 0x0AC8)
class UGA_HighTower_Squash_WhirlwindBlast_Stun_C final : public UGA_Melee_BlockBreak_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Squash_WhirlwindBlast_Stun_C">();
	}
	static class UGA_HighTower_Squash_WhirlwindBlast_Stun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Squash_WhirlwindBlast_Stun_C>();
	}
};

}

