#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Tapas_SkyStrike_Jump_Core

#include "Basic.hpp"

#include "GA_HighTower_Tapas_SkyStrike_Fire_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Tapas_SkyStrike_Jump_Core.GA_HighTower_Tapas_SkyStrike_Jump_Core_C
// 0x0000 (0x0DC0 - 0x0DC0)
class UGA_HighTower_Tapas_SkyStrike_Jump_Core_C final : public UGA_HighTower_Tapas_SkyStrike_Fire_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Tapas_SkyStrike_Jump_Core_C">();
	}
	static class UGA_HighTower_Tapas_SkyStrike_Jump_Core_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Tapas_SkyStrike_Jump_Core_C>();
	}
};

}

