#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Date_ChainLightning_RemoveCoolDown

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Date_ChainLightning_RemoveCoolDown.GA_HighTower_Date_ChainLightning_RemoveCoolDown_C
// 0x0008 (0x0AB0 - 0x0AA8)
class UGA_HighTower_Date_ChainLightning_RemoveCoolDown_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_HighTower_Date_ChainLightning_RemoveCoolDown(int32 EntryPoint);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Date_ChainLightning_RemoveCoolDown_C">();
	}
	static class UGA_HighTower_Date_ChainLightning_RemoveCoolDown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Date_ChainLightning_RemoveCoolDown_C>();
	}
};

}

