#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Athena_Knockback_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp.GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C
// 0x0008 (0x0CE8 - 0x0CE0)
class UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C final : public UGA_Athena_Knockback_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C; // 0x0CE0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C">();
	}
	static class UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Squash_WhirlwindBlast_InitialKnockUp_C>();
	}
};

}

