#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Grape_BrambleShield_CoreBR

#include "Basic.hpp"

#include "GA_HighTower_Grape_BrambleShield_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Grape_BrambleShield_CoreBR.GA_HighTower_Grape_BrambleShield_CoreBR_C
// 0x0000 (0x0EA0 - 0x0EA0)
class UGA_HighTower_Grape_BrambleShield_CoreBR_C final : public UGA_HighTower_Grape_BrambleShield_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Grape_BrambleShield_CoreBR_C">();
	}
	static class UGA_HighTower_Grape_BrambleShield_CoreBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Grape_BrambleShield_CoreBR_C>();
	}
};

}

