#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Grape_BrambleShield_Cancel

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Grape_BrambleShield_Cancel.GA_HighTower_Grape_BrambleShield_Cancel_C
// 0x0010 (0x0AB8 - 0x0AA8)
class UGA_HighTower_Grape_BrambleShield_Cancel_C : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           Event_ForceEndShield;                              // 0x0AB0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_HighTower_Grape_BrambleShield_Cancel(int32 EntryPoint);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Grape_BrambleShield_Cancel_C">();
	}
	static class UGA_HighTower_Grape_BrambleShield_Cancel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Grape_BrambleShield_Cancel_C>();
	}
};

}

