#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Date_ChainLightning_RemoveCoolDown

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_HighTower_Date_ChainLightning_RemoveCoolDown.GA_HighTower_Date_ChainLightning_RemoveCoolDown_C.ExecuteUbergraph_GA_HighTower_Date_ChainLightning_RemoveCoolDown
// 0x0004 (0x0004 - 0x0000)
struct GA_HighTower_Date_ChainLightning_RemoveCoolDown_C_ExecuteUbergraph_GA_HighTower_Date_ChainLightning_RemoveCoolDown final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

