#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_HoneyDew_JumpSmash_Knockback

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GA_HighTower_HoneyDew_JumpSmash_Knockback.GA_HighTower_HoneyDew_JumpSmash_Knockback_C.ExecuteUbergraph_GA_HighTower_HoneyDew_JumpSmash_Knockback
// 0x000C (0x000C - 0x0000)
struct GA_HighTower_HoneyDew_JumpSmash_Knockback_C_ExecuteUbergraph_GA_HighTower_HoneyDew_JumpSmash_Knockback final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToOwner_ReturnValue; // 0x0004(0x0008)(NoDestructor, HasGetValueTypeHash)
};

}

