#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_HoneyDew_Fist_Knockup

#include "Basic.hpp"

#include "GA_Athena_Knockback_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_HoneyDew_Fist_Knockup.GA_HighTower_HoneyDew_Fist_Knockup_C
// 0x0000 (0x0CE0 - 0x0CE0)
class UGA_HighTower_HoneyDew_Fist_Knockup_C final : public UGA_Athena_Knockback_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_HoneyDew_Fist_Knockup_C">();
	}
	static class UGA_HighTower_HoneyDew_Fist_Knockup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_HoneyDew_Fist_Knockup_C>();
	}
};

}

