#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_HoneyDew_Fist_Evade

#include "Basic.hpp"

#include "GA_Melee_Dodge_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_HoneyDew_Fist_Evade.GA_HighTower_HoneyDew_Fist_Evade_C
// 0x0000 (0x0B70 - 0x0B70)
class UGA_HighTower_HoneyDew_Fist_Evade_C final : public UGA_Melee_Dodge_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_HoneyDew_Fist_Evade_C">();
	}
	static class UGA_HighTower_HoneyDew_Fist_Evade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_HoneyDew_Fist_Evade_C>();
	}
};

}

