#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Squash_WhirlwindBlast_Knockback

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GA_HighTower_Squash_WhirlwindBlast_Knockback.GA_HighTower_Squash_WhirlwindBlast_Knockback_C.ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_Knockback
// 0x0018 (0x0018 - 0x0000)
struct GA_HighTower_Squash_WhirlwindBlast_Knockback_C_ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_Knockback final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UAbilitySystemComponent*                CallFunc_GetAbilitySystemComponent_ReturnValue;    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToSelf_ReturnValue; // 0x0010(0x0008)(NoDestructor, HasGetValueTypeHash)
};

}

