#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Hightower_Vertigo_Punch_CoreBR

#include "Basic.hpp"

#include "GA_Hightower_Vertigo_Punch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Hightower_Vertigo_Punch_CoreBR.GA_Hightower_Vertigo_Punch_CoreBR_C
// 0x0000 (0x0FD0 - 0x0FD0)
class UGA_Hightower_Vertigo_Punch_CoreBR_C final : public UGA_Hightower_Vertigo_Punch_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Hightower_Vertigo_Punch_CoreBR_C">();
	}
	static class UGA_Hightower_Vertigo_Punch_CoreBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Hightower_Vertigo_Punch_CoreBR_C>();
	}
};

}

