#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_HighTower_Date_ChainLightning_Ranged_Projectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Ranged_GenericDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_Date_ChainLightning_Ranged_Projectile.GA_HighTower_Date_ChainLightning_Ranged_Projectile_C
// 0x0008 (0x0AF8 - 0x0AF0)
class UGA_HighTower_Date_ChainLightning_Ranged_Projectile_C final : public UGA_Ranged_GenericDamage_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AF0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_HighTower_Date_ChainLightning_Ranged_Projectile(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HighTower_Date_ChainLightning_Ranged_Projectile_C">();
	}
	static class UGA_HighTower_Date_ChainLightning_Ranged_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_Date_ChainLightning_Ranged_Projectile_C>();
	}
};

}

