#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_LowTower_HeldObject_Chaplin_Exposion

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_LowTower_HeldObject_Chaplin_Exposion.GA_LowTower_HeldObject_Chaplin_Exposion_C
// 0x0010 (0x0AB8 - 0x0AA8)
class UGA_LowTower_HeldObject_Chaplin_Exposion_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABuildingGameplayActor*                 TargetSelectionActor;                              // 0x0AB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_LowTower_HeldObject_Chaplin_Exposion(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void Targeted_E0DFECF744FA4E0991DB29AA05C14BEC(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Cancelled_E0DFECF744FA4E0991DB29AA05C14BEC(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);

	struct FTransform GetCustomAbilitySourceTransform() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_LowTower_HeldObject_Chaplin_Exposion_C">();
	}
	static class UGA_LowTower_HeldObject_Chaplin_Exposion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_LowTower_HeldObject_Chaplin_Exposion_C>();
	}
};

}

