#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GasketDataTracker_Mang

#include "Basic.hpp"

#include "GasketDataTracker_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GasketDataTracker_Mang.GasketDataTracker_Mang_C
// 0x0000 (0x01A8 - 0x01A8)
class UGasketDataTracker_Mang_C final : public UGasketDataTracker_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GasketDataTracker_Mang_C">();
	}
	static class UGasketDataTracker_Mang_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGasketDataTracker_Mang_C>();
	}
};

}

