#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GasketDataTracker_Wasabi

#include "Basic.hpp"

#include "GasketDataTracker_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GasketDataTracker_Wasabi.GasketDataTracker_Wasabi_C
// 0x0000 (0x01A8 - 0x01A8)
class UGasketDataTracker_Wasabi_C final : public UGasketDataTracker_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GasketDataTracker_Wasabi_C">();
	}
	static class UGasketDataTracker_Wasabi_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGasketDataTracker_Wasabi_C>();
	}
};

}

