#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GasketDataTracker

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GasketDataTracker.GasketDataTracker_C
// 0x0000 (0x01A8 - 0x01A8)
class UGasketDataTracker_C : public UFortGameplayDataTrackerComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GasketDataTracker_C">();
	}
	static class UGasketDataTracker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGasketDataTracker_C>();
	}
};

}

