#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GasketDataTracker_Tomato

#include "Basic.hpp"

#include "GasketDataTracker_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GasketDataTracker_Tomato.GasketDataTracker_Tomato_C
// 0x0000 (0x01A8 - 0x01A8)
class UGasketDataTracker_Tomato_C final : public UGasketDataTracker_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GasketDataTracker_Tomato_C">();
	}
	static class UGasketDataTracker_Tomato_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGasketDataTracker_Tomato_C>();
	}
};

}

