#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_LowTower_Chaplin_PrjImpact

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_LowTower_Chaplin_PrjImpact.GCN_LowTower_Chaplin_PrjImpact_C
// 0x0000 (0x01B8 - 0x01B8)
class UGCN_LowTower_Chaplin_PrjImpact_C final : public UFortGameplayCueNotify_Burst
{
public:
	void OnBurstGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_LowTower_Chaplin_PrjImpact_C">();
	}
	static class UGCN_LowTower_Chaplin_PrjImpact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_LowTower_Chaplin_PrjImpact_C>();
	}
};

}

