#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Date_ChainLightning_ChainBurst

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Date_ChainLightning_ChainBurst.GCN_HighTower_Date_ChainLightning_ChainBurst_C
// 0x0008 (0x01C0 - 0x01B8)
class UGCN_HighTower_Date_ChainLightning_ChainBurst_C final : public UFortGameplayCueNotify_Burst
{
public:
	float                                         Divisor;                                           // 0x01B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnBurstGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Date_ChainLightning_ChainBurst_C">();
	}
	static class UGCN_HighTower_Date_ChainLightning_ChainBurst_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Date_ChainLightning_ChainBurst_C>();
	}
};

}

