#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_LowTower_Laurel_Shoot

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_LowTower_Laurel_Shoot.GCN_LowTower_Laurel_Shoot_C
// 0x0000 (0x0460 - 0x0460)
class AGCN_LowTower_Laurel_Shoot_C final : public AFortGameplayCueNotify_BurstLatent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_LowTower_Laurel_Shoot_C">();
	}
	static class AGCN_LowTower_Laurel_Shoot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_LowTower_Laurel_Shoot_C>();
	}
};

}

