#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Squash_WhirlwindBlast_KnockBack

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Squash_WhirlwindBlast_KnockBack.GCN_HighTower_Squash_WhirlwindBlast_KnockBack_C
// 0x0000 (0x01B8 - 0x01B8)
class UGCN_HighTower_Squash_WhirlwindBlast_KnockBack_C final : public UFortGameplayCueNotify_Burst
{
public:
	void OnBurstNiagara(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UNiagaraComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Squash_WhirlwindBlast_KnockBack_C">();
	}
	static class UGCN_HighTower_Squash_WhirlwindBlast_KnockBack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Squash_WhirlwindBlast_KnockBack_C>();
	}
};

}

