#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Tomato_RepulsorCannon_StructureHit

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Tomato_RepulsorCannon_StructureHit.GCN_HighTower_Tomato_RepulsorCannon_StructureHit_C
// 0x0000 (0x01B8 - 0x01B8)
class UGCN_HighTower_Tomato_RepulsorCannon_StructureHit_C final : public UFortGameplayCueNotify_Burst
{
public:
	void OnBurstGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;
	void SpawnSoundIndicators(class AActor* Target, const struct FGameplayCueParameters& Params_0) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Tomato_RepulsorCannon_StructureHit_C">();
	}
	static class UGCN_HighTower_Tomato_RepulsorCannon_StructureHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Tomato_RepulsorCannon_StructureHit_C>();
	}
};

}

