#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Date_ChainLightning_Explode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Date_ChainLightning_Explode.GCN_HighTower_Date_ChainLightning_Explode_C
// 0x0008 (0x01C0 - 0x01B8)
class UGCN_HighTower_Date_ChainLightning_Explode_C final : public UFortGameplayCueNotify_Burst
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GCN_HighTower_Date_ChainLightning_Explode(int32 EntryPoint);
	void Explode_Audio();

	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Date_ChainLightning_Explode_C">();
	}
	static class UGCN_HighTower_Date_ChainLightning_Explode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Date_ChainLightning_Explode_C>();
	}
};

}

