#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Wasabi_Claws_Finisher_Impact

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Wasabi_Claws_Finisher_Impact.GCN_HighTower_Wasabi_Claws_Finisher_Impact_C
// 0x0008 (0x01C0 - 0x01B8)
class UGCN_HighTower_Wasabi_Claws_Finisher_Impact_C final : public UFortGameplayCueNotify_Burst
{
public:
	class UAnimMontage*                           FullBodyHitMontage;                                // 0x01B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Wasabi_Claws_Finisher_Impact_C">();
	}
	static class UGCN_HighTower_Wasabi_Claws_Finisher_Impact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Wasabi_Claws_Finisher_Impact_C>();
	}
};

}

