#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_HoneyDew_Swing_4

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_HoneyDew_Swing_4.GCN_HighTower_HoneyDew_Swing_4_C
// 0x0000 (0x01B8 - 0x01B8)
class UGCN_HighTower_HoneyDew_Swing_4_C final : public UFortGameplayCueNotify_Burst
{
public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_HoneyDew_Swing_4_C">();
	}
	static class UGCN_HighTower_HoneyDew_Swing_4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_HoneyDew_Swing_4_C>();
	}
};

}

