#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_LowTower_Laurel_PreAttack

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_LowTower_Laurel_PreAttack.GCN_LowTower_Laurel_PreAttack_C
// 0x0000 (0x01B8 - 0x01B8)
class UGCN_LowTower_Laurel_PreAttack_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_LowTower_Laurel_PreAttack_C">();
	}
	static class UGCN_LowTower_Laurel_PreAttack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_LowTower_Laurel_PreAttack_C>();
	}
};

}

