#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Tapas_Skystrike_Cast

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Tapas_Skystrike_Cast.GCN_HighTower_Tapas_Skystrike_Cast_C
// 0x0008 (0x01C0 - 0x01B8)
class UGCN_HighTower_Tapas_Skystrike_Cast_C final : public UFortGameplayCueNotify_Burst
{
public:
	class UParticleSystem*                        P_SkyStrike_Lightning;                             // 0x01B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Tapas_Skystrike_Cast_C">();
	}
	static class UGCN_HighTower_Tapas_Skystrike_Cast_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Tapas_Skystrike_Cast_C>();
	}
};

}

