#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_HighTower_Grape_BrambleShield_Damaged

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_HighTower_Grape_BrambleShield_Damaged.GCN_HighTower_Grape_BrambleShield_Damaged_C
// 0x0000 (0x01B8 - 0x01B8)
class UGCN_HighTower_Grape_BrambleShield_Damaged_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_HighTower_Grape_BrambleShield_Damaged_C">();
	}
	static class UGCN_HighTower_Grape_BrambleShield_Damaged_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_HighTower_Grape_BrambleShield_Damaged_C>();
	}
};

}

