#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNL_Honeydew_Fist_Dodge

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Honeydew_Fist_Dodge.GCNL_Honeydew_Fist_Dodge_C
// 0x0000 (0x07C0 - 0x07C0)
class AGCNL_Honeydew_Fist_Dodge_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_Honeydew_Fist_Dodge_C">();
	}
	static class AGCNL_Honeydew_Fist_Dodge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Honeydew_Fist_Dodge_C>();
	}
};

}

