#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNL_HighTower_HoneyDew_JumpSmash_LowGrav

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_HighTower_HoneyDew_JumpSmash_LowGrav.GCNL_HighTower_HoneyDew_JumpSmash_LowGrav_C
// 0x0000 (0x07C0 - 0x07C0)
class AGCNL_HighTower_HoneyDew_JumpSmash_LowGrav_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_HighTower_HoneyDew_JumpSmash_LowGrav_C">();
	}
	static class AGCNL_HighTower_HoneyDew_JumpSmash_LowGrav_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_HighTower_HoneyDew_JumpSmash_LowGrav_C>();
	}
};

}

