#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNL_HighTower_Grape_BrambleShield_AuraTrails

#include "Basic.hpp"

#include "GCNL_HighTower_Trails_Utility_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_HighTower_Grape_BrambleShield_AuraTrails.GCNL_HighTower_Grape_BrambleShield_AuraTrails_C
// 0x0000 (0x0828 - 0x0828)
class AGCNL_HighTower_Grape_BrambleShield_AuraTrails_C final : public AGCNL_HighTower_Trails_Utility_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_HighTower_Grape_BrambleShield_AuraTrails_C">();
	}
	static class AGCNL_HighTower_Grape_BrambleShield_AuraTrails_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_HighTower_Grape_BrambleShield_AuraTrails_C>();
	}
};

}

