#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Athena_CandyCorn

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Athena_CandyCorn.GE_Athena_CandyCorn_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Athena_CandyCorn_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Athena_CandyCorn_C">();
	}
	static class UGE_Athena_CandyCorn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Athena_CandyCorn_C>();
	}
};

}

