#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Galileo_Lobster_Dodge_Cooldown

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Galileo_Lobster_Dodge_Cooldown.GE_Galileo_Lobster_Dodge_Cooldown_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Galileo_Lobster_Dodge_Cooldown_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Galileo_Lobster_Dodge_Cooldown_C">();
	}
	static class UGE_Galileo_Lobster_Dodge_Cooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Galileo_Lobster_Dodge_Cooldown_C>();
	}
};

}

