#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond.GE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond_C
// 0x0010 (0x0038 - 0x0028)
class UGE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond_C final : public UGameplayEffectCustomApplicationRequirement
{
public:
	TArray<struct FGameplayTag>                   ForbiddenActorTagList;                             // 0x0028(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	bool CanApplyGameplayEffect(const class UGameplayEffect* GameplayEffect, const struct FGameplayEffectSpec& Spec, class UAbilitySystemComponent* ASC) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond_C">();
	}
	static class UGE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_SquashWhirlwindBlast_InitialKnockBackUpwardCond_C>();
	}
};

}

