#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HealthRegenPercent_Parent

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HealthRegenPercent_Parent.GE_HealthRegenPercent_Parent_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HealthRegenPercent_Parent_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HealthRegenPercent_Parent_C">();
	}
	static class UGE_HealthRegenPercent_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HealthRegenPercent_Parent_C>();
	}
};

}

