#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_Wasabi_Claws_GrantedTag

#include "Basic.hpp"

#include "GE_HighTower_GrantedTag_Primary_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Wasabi_Claws_GrantedTag.GE_HighTower_Wasabi_Claws_GrantedTag_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Wasabi_Claws_GrantedTag_C : public UGE_HighTower_GrantedTag_Primary_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Wasabi_Claws_GrantedTag_C">();
	}
	static class UGE_HighTower_Wasabi_Claws_GrantedTag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Wasabi_Claws_GrantedTag_C>();
	}
};

}

