#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_Tapas_SkyStrike_Knockback

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Tapas_SkyStrike_Knockback.GE_HighTower_Tapas_SkyStrike_Knockback_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Tapas_SkyStrike_Knockback_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Tapas_SkyStrike_Knockback_C">();
	}
	static class UGE_HighTower_Tapas_SkyStrike_Knockback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Tapas_SkyStrike_Knockback_C>();
	}
};

}

