#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR

#include "Basic.hpp"

#include "GE_HighTower_Grape_BrambleShield_GrantedTag_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR.GE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR_C final : public UGE_HighTower_Grape_BrambleShield_GrantedTag_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR_C">();
	}
	static class UGE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Grape_BrambleShield_GrantedTag_CoreBR_C>();
	}
};

}

