#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_Date_ChainLightning_Boost_Cooldown

#include "Basic.hpp"

#include "GET_Cooldown_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Date_ChainLightning_Boost_Cooldown.GE_HighTower_Date_ChainLightning_Boost_Cooldown_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Date_ChainLightning_Boost_Cooldown_C final : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Date_ChainLightning_Boost_Cooldown_C">();
	}
	static class UGE_HighTower_Date_ChainLightning_Boost_Cooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Date_ChainLightning_Boost_Cooldown_C>();
	}
};

}

