#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Hightower_Wasabi_Claws_DoubleHit_Damage

#include "Basic.hpp"

#include "GE_Melee_GenericDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Hightower_Wasabi_Claws_DoubleHit_Damage.GE_Hightower_Wasabi_Claws_DoubleHit_Damage_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Hightower_Wasabi_Claws_DoubleHit_Damage_C final : public UGE_Melee_GenericDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Hightower_Wasabi_Claws_DoubleHit_Damage_C">();
	}
	static class UGE_Hightower_Wasabi_Claws_DoubleHit_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Hightower_Wasabi_Claws_DoubleHit_Damage_C>();
	}
};

}

