#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown

#include "Basic.hpp"

#include "GE_HighTower_Cooldown_InfiniteDuration_Jump_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown.GE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown_C final : public UGE_HighTower_Cooldown_InfiniteDuration_Jump_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown_C">();
	}
	static class UGE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_HoneyDew_JumpSmash_Smash_InfCooldown_C>();
	}
};

}

