#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Honeydew_Fist_Dodge_West

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Honeydew_Fist_Dodge_West.GE_Honeydew_Fist_Dodge_West_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Honeydew_Fist_Dodge_West_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Honeydew_Fist_Dodge_West_C">();
	}
	static class UGE_Honeydew_Fist_Dodge_West_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Honeydew_Fist_Dodge_West_C>();
	}
};

}

