#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HopDrop_LowGravity_UsingJump

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HopDrop_LowGravity_UsingJump.GE_HopDrop_LowGravity_UsingJump_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HopDrop_LowGravity_UsingJump_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HopDrop_LowGravity_UsingJump_C">();
	}
	static class UGE_HopDrop_LowGravity_UsingJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HopDrop_LowGravity_UsingJump_C>();
	}
};

}

