#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_Wasabi_Claws_HealthRegen

#include "Basic.hpp"

#include "GE_HealthRegenPercent_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Wasabi_Claws_HealthRegen.GE_HighTower_Wasabi_Claws_HealthRegen_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Wasabi_Claws_HealthRegen_C final : public UGE_HealthRegenPercent_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Wasabi_Claws_HealthRegen_C">();
	}
	static class UGE_HighTower_Wasabi_Claws_HealthRegen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Wasabi_Claws_HealthRegen_C>();
	}
};

}

