#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_HighTower_Date_BallLightning_ExplodeEnvironment

#include "Basic.hpp"

#include "GET_DirectPhysicalDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HighTower_Date_BallLightning_ExplodeEnvironment.GE_HighTower_Date_BallLightning_ExplodeEnvironment_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HighTower_Date_BallLightning_ExplodeEnvironment_C final : public UGET_DirectPhysicalDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HighTower_Date_BallLightning_ExplodeEnvironment_C">();
	}
	static class UGE_HighTower_Date_BallLightning_ExplodeEnvironment_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HighTower_Date_BallLightning_ExplodeEnvironment_C>();
	}
};

}

