#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_JellyBean

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_JellyBean.GE_JellyBean_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_JellyBean_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_JellyBean_C">();
	}
	static class UGE_JellyBean_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_JellyBean_C>();
	}
};

}

