#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_LowTower_Chaplin_ChargeProjectile

#include "Basic.hpp"

#include "GE_Ranged_GenericDamage_Explosive_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_LowTower_Chaplin_ChargeProjectile.GE_LowTower_Chaplin_ChargeProjectile_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_LowTower_Chaplin_ChargeProjectile_C final : public UGE_Ranged_GenericDamage_Explosive_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_LowTower_Chaplin_ChargeProjectile_C">();
	}
	static class UGE_LowTower_Chaplin_ChargeProjectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_LowTower_Chaplin_ChargeProjectile_C>();
	}
};

}

