#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Melee_Dodge_South

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Melee_Dodge_South.GE_Melee_Dodge_South_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Melee_Dodge_South_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Melee_Dodge_South_C">();
	}
	static class UGE_Melee_Dodge_South_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Melee_Dodge_South_C>();
	}
};

}

