#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Melee_Dodge_East

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Melee_Dodge_East.GE_Melee_Dodge_East_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Melee_Dodge_East_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Melee_Dodge_East_C">();
	}
	static class UGE_Melee_Dodge_East_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Melee_Dodge_East_C>();
	}
};

}

