#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_PepperMint_Speed

#include "Basic.hpp"

#include "GE_SpicyMoveSpeed_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_PepperMint_Speed.GE_PepperMint_Speed_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_PepperMint_Speed_C final : public UGE_SpicyMoveSpeed_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_PepperMint_Speed_C">();
	}
	static class UGE_PepperMint_Speed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_PepperMint_Speed_C>();
	}
};

}

