#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Ranged_IsTargeting_DmgBuff_Stark

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Ranged_IsTargeting_DmgBuff_Stark.GE_Ranged_IsTargeting_DmgBuff_Stark_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Ranged_IsTargeting_DmgBuff_Stark_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Ranged_IsTargeting_DmgBuff_Stark_C">();
	}
	static class UGE_Ranged_IsTargeting_DmgBuff_Stark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Ranged_IsTargeting_DmgBuff_Stark_C>();
	}
};

}

