#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Trap_FrostedTips_Damage

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Trap_FrostedTips_Damage.GE_Trap_FrostedTips_Damage_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Trap_FrostedTips_Damage_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Trap_FrostedTips_Damage_C">();
	}
	static class UGE_Trap_FrostedTips_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Trap_FrostedTips_Damage_C>();
	}
};

}

