#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_ThermalTaffy_Heal

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ThermalTaffy_Heal.GE_ThermalTaffy_Heal_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_ThermalTaffy_Heal_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_ThermalTaffy_Heal_C">();
	}
	static class UGE_ThermalTaffy_Heal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ThermalTaffy_Heal_C>();
	}
};

}

