#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GECAR_Athena_Knockback_Parent

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GECAR_Athena_Knockback_Parent.GECAR_Athena_Knockback_Parent_C
// 0x0010 (0x0038 - 0x0028)
class UGECAR_Athena_Knockback_Parent_C final : public UGameplayEffectCustomApplicationRequirement
{
public:
	struct FGameplayTag                           Tag_BuildingActor;                                 // 0x0028(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Tag_BuildingActorWithPhysics;                      // 0x0030(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	bool CanApplyGameplayEffect(const class UGameplayEffect* GameplayEffect, const struct FGameplayEffectSpec& Spec, class UAbilitySystemComponent* ASC) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GECAR_Athena_Knockback_Parent_C">();
	}
	static class UGECAR_Athena_Knockback_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGECAR_Athena_Knockback_Parent_C>();
	}
};

}

