#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HighTower_Tomato_CameraShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HighTower_Tomato_CameraShake.HighTower_Tomato_CameraShake_C
// 0x0000 (0x0190 - 0x0190)
class UHighTower_Tomato_CameraShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HighTower_Tomato_CameraShake_C">();
	}
	static class UHighTower_Tomato_CameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighTower_Tomato_CameraShake_C>();
	}
};

}

