#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HighTower_Tomato_RepulsorCannon_CameraMode

#include "Basic.hpp"

#include "Athena_PlayerCameraModeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HighTower_Tomato_RepulsorCannon_CameraMode.HighTower_Tomato_RepulsorCannon_CameraMode_C
// 0x0000 (0x0DD0 - 0x0DD0)
class UHighTower_Tomato_RepulsorCannon_CameraMode_C final : public UAthena_PlayerCameraModeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HighTower_Tomato_RepulsorCannon_CameraMode_C">();
	}
	static class UHighTower_Tomato_RepulsorCannon_CameraMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighTower_Tomato_RepulsorCannon_CameraMode_C>();
	}
};

}

