#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HighTowerRuntime

#include "Basic.hpp"


namespace SDK::Params
{

// Function HighTowerRuntime.FortAthenaMutator_HighTowerAbilityIntro.OnBeginSkydiveFromBus
// 0x0008 (0x0008 - 0x0000)
struct FortAthenaMutator_HighTowerAbilityIntro_OnBeginSkydiveFromBus final
{
public:
	class AFortPlayerControllerZone*              PlayerController;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

