#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HighTower_PlayerCameraMode_Date_ChainLightning_Targeting

#include "Basic.hpp"

#include "Athena_PlayerCameraModeRangedTargeting_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HighTower_PlayerCameraMode_Date_ChainLightning_Targeting.HighTower_PlayerCameraMode_Date_ChainLightning_Targeting_C
// 0x0000 (0x0DD0 - 0x0DD0)
class UHighTower_PlayerCameraMode_Date_ChainLightning_Targeting_C final : public UAthena_PlayerCameraModeRangedTargeting_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HighTower_PlayerCameraMode_Date_ChainLightning_Targeting_C">();
	}
	static class UHighTower_PlayerCameraMode_Date_ChainLightning_Targeting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighTower_PlayerCameraMode_Date_ChainLightning_Targeting_C>();
	}
};

}

