#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HighTowerUI

#include "Basic.hpp"

#include "HighTowerUI_classes.hpp"


namespace SDK
{

// Function HighTowerUI.HighTowerAbilityContainerWidget.ShowAbilityIntro
// (Event, Protected, BlueprintEvent)

void UHighTowerAbilityContainerWidget::ShowAbilityIntro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HighTowerAbilityContainerWidget", "ShowAbilityIntro");

	UObject::ProcessEvent(Func, nullptr);
}

}

