#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HighTowerUI

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class HighTowerUI.HighTowerAbilityContainerWidget
// 0x0008 (0x0320 - 0x0318)
class UHighTowerAbilityContainerWidget final : public ULTMWidgetBase
{
public:
	struct FGameplayTag                           ShowAbilityIntroTag;                               // 0x0318(0x0008)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void ShowAbilityIntro();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"HighTowerAbilityContainerWidget">();
	}
	static class UHighTowerAbilityContainerWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighTowerAbilityContainerWidget>();
	}
};

}

