#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: HoagieUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class HoagieUI.FortHoagieVehicleReticle
// 0x0010 (0x02D8 - 0x02C8)
class UFortHoagieVehicleReticle final : public UFortHUDElementWidget
{
public:
	uint8                                         Pad_2C8[0x8];                                      // 0x02C8(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	class AFortHoagieVehicle*                     OwningHoagieVehicle;                               // 0x02D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnSetupComplete();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortHoagieVehicleReticle">();
	}
	static class UFortHoagieVehicleReticle* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortHoagieVehicleReticle>();
	}
};

}

