#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ItemShopSelector

#include "Basic.hpp"


namespace SDK::Params
{

// Function ItemShopSelector.ItemShopSelector_C.ExecuteUbergraph_ItemShopSelector
// 0x0004 (0x0004 - 0x0000)
struct ItemShopSelector_C_ExecuteUbergraph_ItemShopSelector final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

