#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: JCountDown_Vis

#include "Basic.hpp"

#include "JCountDown_Vis_classes.hpp"
#include "JCountDown_Vis_parameters.hpp"


namespace SDK
{

// Function JCountDown_Vis.JCountDown_Vis_C.ExecuteUbergraph_JCountDown_Vis
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AJCountDown_Vis_C::ExecuteUbergraph_JCountDown_Vis(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JCountDown_Vis_C", "ExecuteUbergraph_JCountDown_Vis");

	Params::JCountDown_Vis_C_ExecuteUbergraph_JCountDown_Vis Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function JCountDown_Vis.JCountDown_Vis_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AJCountDown_Vis_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JCountDown_Vis_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

