#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: JCountDown_Vis

#include "Basic.hpp"


namespace SDK::Params
{

// Function JCountDown_Vis.JCountDown_Vis_C.ExecuteUbergraph_JCountDown_Vis
// 0x0004 (0x0004 - 0x0000)
struct JCountDown_Vis_C_ExecuteUbergraph_JCountDown_Vis final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

