#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: LowTowerDataTracker

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LowTowerDataTracker.LowTowerDataTracker_C
// 0x0000 (0x01A8 - 0x01A8)
class ULowTowerDataTracker_C final : public UFortGameplayDataTrackerComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LowTowerDataTracker_C">();
	}
	static class ULowTowerDataTracker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULowTowerDataTracker_C>();
	}
};

}

