#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: M_MED_HighTower_Tomato_FaceAcc_AnimBp

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function M_MED_HighTower_Tomato_FaceAcc_AnimBp.M_MED_HighTower_Tomato_FaceAcc_AnimBp_C.ExecuteUbergraph_M_MED_HighTower_Tomato_FaceAcc_AnimBp
// 0x0004 (0x0004 - 0x0000)
struct M_MED_HighTower_Tomato_FaceAcc_AnimBp_C_ExecuteUbergraph_M_MED_HighTower_Tomato_FaceAcc_AnimBp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function M_MED_HighTower_Tomato_FaceAcc_AnimBp.M_MED_HighTower_Tomato_FaceAcc_AnimBp_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct M_MED_HighTower_Tomato_FaceAcc_AnimBp_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

}

