#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: M_MED_HighTower_Tapas_AnimBP_0

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass M_MED_HighTower_Tapas_AnimBP.M_MED_HighTower_Tapas_AnimBP_C
// 0x2040 (0x2520 - 0x04E0)
class M_MED_HighTower_Tapas_AnimBP_0::UM_MED_HighTower_Tapas_AnimBP_C final : public UCustomCharacterPartAnimInstance_HightowerTapasTop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x04E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4E9[0x7];                                      // 0x04E9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x04F0(0x0140)(ContainsInstancedReference)
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0630(0x0660)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x0C90(0x0020)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_4;                            // 0x0CB0(0x01B0)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_3;                            // 0x0E60(0x01B0)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_2;                            // 0x1010(0x01B0)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_1;                        // 0x11C0(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x12C8(0x0028)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint;                          // 0x12F0(0x0108)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x13F8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x1428(0x0028)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_10;                       // 0x1450(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_9;                        // 0x1558(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_8;                        // 0x1660(0x0108)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x1768(0x0020)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x1788(0x00C8)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_7;                        // 0x1850(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_6;                        // 0x1958(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_5;                        // 0x1A60(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x1B68(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x1C70(0x0108)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x1D78(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x1D98(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x1EA0(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x1FA8(0x0108)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_1;                            // 0x20B0(0x01B0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x2260(0x00A0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x2300(0x0020)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt;                              // 0x2320(0x01B0)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x24D0(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x24F0(0x0020)()
	float                                         IsTargetingAlpha;                                  // 0x2510(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         IsWearingBackblingAlpha;                           // 0x2514(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_M_MED_HighTower_Tapas_AnimBP(int32 EntryPoint);
	void OnCharacterCustomizationLoaded();
	void OnEndSkydiving();
	void OnEndTargeting();
	void OnBeginTargeting();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBlueprintGeneratedClass M_MED_HighTower_Tapas_AnimBP.M_MED_HighTower_Tapas_AnimBP_C", true, "M_MED_HighTower_Tapas_AnimBP_C">();
	}
	static class M_MED_HighTower_Tapas_AnimBP_0::UM_MED_HighTower_Tapas_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<M_MED_HighTower_Tapas_AnimBP_0::UM_MED_HighTower_Tapas_AnimBP_C>();
	}
};

}

