#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: M_MED_HighTower_Tomato_FaceAcc_AnimBp

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass M_MED_HighTower_Tomato_FaceAcc_AnimBp.M_MED_HighTower_Tomato_FaceAcc_AnimBp_C
// 0x0180 (0x0440 - 0x02C0)
class UM_MED_HighTower_Tomato_FaceAcc_AnimBp_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02D0(0x0030)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x0300(0x0140)(ContainsInstancedReference)

public:
	void ExecuteUbergraph_M_MED_HighTower_Tomato_FaceAcc_AnimBp(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"M_MED_HighTower_Tomato_FaceAcc_AnimBp_C">();
	}
	static class UM_MED_HighTower_Tomato_FaceAcc_AnimBp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UM_MED_HighTower_Tomato_FaceAcc_AnimBp_C>();
	}
};

}

