#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: M_MED_HighTower_Tapas_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass M_MED_HighTower_Tapas_AnimBP.M_MED_HighTower_Tapas_AnimBP_C
// 0x3330 (0x3820 - 0x04F0)
class M_MED_HighTower_Tapas_AnimBP::UM_MED_HighTower_Tapas_AnimBP_C final : public UCustomCharacterPartAnimInstance_HightowerTapasBody
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x04F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F9[0x7];                                      // 0x04F9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0500(0x0030)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x0530(0x0140)(ContainsInstancedReference)
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0670(0x0660)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0CD0(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0CF0(0x0020)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_16;                       // 0x0D10(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_15;                       // 0x0E18(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_14;                       // 0x0F20(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_13;                       // 0x1028(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_12;                       // 0x1130(0x0108)()
	uint8                                         Pad_1238[0x8];                                     // 0x1238(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_3;                            // 0x1240(0x01B0)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_2;                            // 0x13F0(0x01B0)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_1;                            // 0x15A0(0x01B0)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_17;                       // 0x1750(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_11;                       // 0x1858(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_10;                       // 0x1960(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_16;                       // 0x1A68(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_9;                        // 0x1B70(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_8;                        // 0x1C78(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_15;                       // 0x1D80(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_7;                        // 0x1E88(0x0108)()
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt;                              // 0x1F90(0x01B0)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_6;                        // 0x2140(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_14;                       // 0x2248(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_13;                       // 0x2350(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_12;                       // 0x2458(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_11;                       // 0x2560(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_10;                       // 0x2668(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_9;                        // 0x2770(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_5;                        // 0x2878(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_4;                        // 0x2980(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_8;                        // 0x2A88(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_7;                        // 0x2B90(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_6;                        // 0x2C98(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_5;                        // 0x2DA0(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x2EA8(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x2FB0(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_3;                        // 0x30B8(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_2;                        // 0x31C0(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x32C8(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint_1;                        // 0x33D0(0x0108)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint;                          // 0x34D8(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x35E0(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x36E8(0x0108)()
	class UAnimMontage*                           NewVar_0;                                          // 0x37F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           NewVar_1;                                          // 0x37F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           NewVar_2;                                          // 0x3800(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NewVar_3;                                          // 0x3808(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         isFrontendAndSkydivingAlpha;                       // 0x380C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         tapasGliderAlpha;                                  // 0x3810(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_M_MED_HighTower_Tapas_AnimBP(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void OnCharacterCustomizationLoaded();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBlueprintGeneratedClass M_MED_HighTower_Tapas_AnimBP.M_MED_HighTower_Tapas_AnimBP_C", true, "M_MED_HighTower_Tapas_AnimBP_C">();
	}
	static class M_MED_HighTower_Tapas_AnimBP::UM_MED_HighTower_Tapas_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<M_MED_HighTower_Tapas_AnimBP::UM_MED_HighTower_Tapas_AnimBP_C>();
	}
};

}

