#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Male_Medium_HighTower_Tapas_Head_AnimBP

#include "Basic.hpp"

#include "Fortnite_Base_Head_Export_Skeleton_AnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Male_Medium_HighTower_Tapas_Head_AnimBP.Male_Medium_HighTower_Tapas_Head_AnimBP_C
// 0x0000 (0x15A0 - 0x15A0)
class UMale_Medium_HighTower_Tapas_Head_AnimBP_C final : public UFortnite_Base_Head_Export_Skeleton_AnimBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Male_Medium_HighTower_Tapas_Head_AnimBP_C">();
	}
	static class UMale_Medium_HighTower_Tapas_Head_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMale_Medium_HighTower_Tapas_Head_AnimBP_C>();
	}
};

}

