#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MissionGen_Argon

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_Argon.MissionGen_Argon_C
// 0x0000 (0x06C0 - 0x06C0)
class UMissionGen_Argon_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionGen_Argon_C">();
	}
	static class UMissionGen_Argon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_Argon_C>();
	}
};

}

