#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Trap_Wall_FrostedTips

#include "Basic.hpp"

#include "Trap_Floor_FrostedTips_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Trap_Wall_FrostedTips.Trap_Wall_FrostedTips_C
// 0x0000 (0x0EA0 - 0x0EA0)
class ATrap_Wall_FrostedTips_C final : public ATrap_Floor_FrostedTips_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Trap_Wall_FrostedTips_C">();
	}
	static class ATrap_Wall_FrostedTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATrap_Wall_FrostedTips_C>();
	}
};

}

