#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WhipTracker_Hightower_Date_BallLightning

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WhipTracker_Hightower_Date_BallLightning.WhipTracker_Hightower_Date_BallLightning_C
// 0x0000 (0x00F0 - 0x00F0)
class UWhipTracker_Hightower_Date_BallLightning_C final : public UBulletWhipTrackerComponentBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WhipTracker_Hightower_Date_BallLightning_C">();
	}
	static class UWhipTracker_Hightower_Date_BallLightning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWhipTracker_Hightower_Date_BallLightning_C>();
	}
};

}

