#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WhipTracker_Lowtower_Laurel

#include "Basic.hpp"

#include "BulletWhipTrackerComponent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WhipTracker_Lowtower_Laurel.WhipTracker_Lowtower_Laurel_C
// 0x0000 (0x00F0 - 0x00F0)
class UWhipTracker_Lowtower_Laurel_C final : public UBulletWhipTrackerComponent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WhipTracker_Lowtower_Laurel_C">();
	}
	static class UWhipTracker_Lowtower_Laurel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWhipTracker_Lowtower_Laurel_C>();
	}
};

}

